app/apps/usuarios/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
urlpatterns = [
    # path('cliente/<int:id_cliente>',views.cliente, name="cliente"),
    # path('listado-clientes',views.listado_clientes, name = "listado_clientes"), 

    path('registro-usuarios', views.signup, name="registroUsuarios"),
    path('logout', views.logout, name="logout"),
    path('listado-usuarios', views.listado_usuarios, name="listadoUsuarios"),
    path('desactivar_usuario', views.cambiar_estatus_usuario, name="desactivarUsuario"),
    path('actualizar-usuario/<int:id_usuario>',views.user_data,name="actualizarUsuario"),
    path('metodoActualizar',views.update_user,name="metodoActualizar")

    # path('login', views.login, name="login"),
    # path('prueba', views.login, name="pruebausuarios"),
]

app/pikitPortalAdmin/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import login,logout
from django.views.generic.base import TemplateView # new
from administrationProfile import views
from usuarios import views as seccion_usuarios


urlpatterns = [
    path('',seccion_usuarios.user_login, name="customLogin"),
    path('admin/', admin.site.urls),
    path('administrationProfile/', include('administrationProfile.urls')),
    path('clientes/',include('clientes.urls')),
    path('usuarios/',include('usuarios.urls')),
    path('vendedores/',include('vendedores.urls')),
    path('portal/',include('generic.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', login,{'template_name':'templates/registration/login.html'}, name='home'),
    path('emoji/', include('emoji.urls')),
]

app/apps/usuarios/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.contrib.auth.models import AbstractUser




# class User(AbstractUser):
#     is_administrador =  models.BooleanField(default=False)
#     is_supervisor =  models.BooleanField(default=False)
#     is_gerente_ventas =  models.BooleanField(default=False)
#     is_vendedor =  models.BooleanField(default=False)


# class Role(models.Model):
#     # ADMINISTRADOR = 1
#     # SUPERVISOR = 2
#     # GERENTE_VENTAS = 3
#     # VENDEDOR = 4
#     # ROLE_CHOICES = (
#     #   (ADMINISTRADOR, 'administrador'),
#     #   (SUPERVISOR, 'supervisor'),
#     #   (GERENTE_VENTAS, 'gerente_ventas'),
#     #   (VENDEDOR, 'vendedor'),)
#     id =  models.IntegerField()
#     usuario = models.ForeignKey('AuthUser',on_delete=models.CASCADE)
#     tipo = models.OneToOneField('User', on_delete=models.CASCADE, primary_key=True)
       

#     class Meta:
#         managed = True
#         db_table = "roles"
#     # def __str__(self):
    #   return self.get_id_display()


class ApiKeys(models.Model):
    api_key = models.CharField(primary_key=True, max_length=128)
    date_creation = models.DateTimeField()
    date_modification = models.DateTimeField()
    active = models.IntegerField()
    user_id = models.PositiveIntegerField()

    class Meta:
        managed = False
        db_table = 'api_keys'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()
    

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Clientes(models.Model):
    category_id = models.IntegerField(blank=True, null=True)
    nombre = models.CharField(max_length=250)
    perfil = models.IntegerField()
    telefono = models.CharField(max_length=50)
    direccion = models.CharField(max_length=250)
    estado = models.IntegerField()
    ciudad = models.IntegerField()
    cp = models.PositiveIntegerField(blank=True, null=True)
    email = models.CharField(max_length=250)
    password = models.CharField(max_length=250)
    clave = models.CharField(max_length=250, blank=True, null=True)
    confirmado = models.IntegerField()
    tipo_inscripcion = models.IntegerField(blank=True, null=True)
    razon_social = models.CharField(max_length=250, blank=True, null=True)
    rfc = models.CharField(max_length=250, blank=True, null=True)
    email_fac = models.CharField(max_length=250, blank=True, null=True)
    calle_fac = models.CharField(max_length=250, blank=True, null=True)
    numero_fac = models.CharField(max_length=250, blank=True, null=True)
    colonia_fac = models.CharField(max_length=250, blank=True, null=True)
    cp_fac = models.IntegerField(blank=True, null=True)
    estado_fac = models.IntegerField(blank=True, null=True)
    ciudad_fac = models.CharField(max_length=250, blank=True, null=True)
    nombre_contacto = models.CharField(max_length=250, blank=True, null=True)
    apellido_contacto = models.CharField(max_length=250, blank=True, null=True)
    telefono_contacto = models.CharField(max_length=250, blank=True, null=True)
    email_contacto = models.CharField(max_length=250, blank=True, null=True)
    filetype = models.CharField(max_length=4, blank=True, null=True)
    update_email = models.CharField(max_length=250, blank=True, null=True)
    idcostumeropenpay = models.CharField(db_column='idCostumerOpenPay', max_length=250, blank=True, null=True)  # Field name made lowercase.
    idtdcopenpay = models.CharField(db_column='idTdcOpenPay', max_length=250, blank=True, null=True)  # Field name made lowercase.
    digitscard = models.IntegerField(db_column='digitsCard', blank=True, null=True)  # Field name made lowercase.
    idsubsopenpay = models.CharField(db_column='idSubsOpenPay', max_length=250, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'clientes'


class ClientesUsuarios(models.Model):
    nombre = models.CharField(max_length=250)
    telefono = models.CharField(max_length=250)
    id_sucursal = models.PositiveIntegerField()
    email = models.CharField(max_length=250)
    password = models.CharField(max_length=250)
    id_cliente = models.PositiveIntegerField()
    clave = models.CharField(max_length=250, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'clientes_usuarios'


class ClientesUsuariosSucursalesRel(models.Model):
    id_usuario = models.PositiveIntegerField()
    id_sucursal = models.PositiveIntegerField()
    activo = models.PositiveIntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'clientes_usuarios_sucursales_rel'


class ClientsCategories(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        managed = False
        db_table = 'clients_categories'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Estados(models.Model):
    clave = models.CharField(max_length=2)
    name = models.CharField(max_length=45)
    abrev = models.CharField(max_length=16)
    abrev_pm = models.CharField(max_length=16)
    id_country = models.IntegerField(blank=True, null=True)
    activo = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'estados'


class Logsopenpay(models.Model):
    error = models.TextField(blank=True, null=True)
    request = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'logsOpenPay'


class MerchantLocationsImages(models.Model):
    merchant_location_id = models.PositiveIntegerField()
    image_order = models.PositiveIntegerField()
    filetype = models.CharField(max_length=4)

    class Meta:
        managed = False
        db_table = 'merchant_locations_images'


class Municipios(models.Model):
    estado_id = models.IntegerField()
    clave = models.IntegerField()
    name = models.CharField(max_length=50)
    sigla = models.CharField(max_length=4)
    active = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'municipios'


class Publicaciones(models.Model):
    # id_cliente = models.PositiveIntegerField()
    id_cliente = models.ForeignKey('Clientes',on_delete=models.CASCADE, db_column='id_cliente')
    titulo = models.CharField(max_length=250)
    descripcion = models.TextField(blank=True, null=True)
    horario_apertura = models.PositiveIntegerField()
    horario_cierre = models.PositiveIntegerField()

app/apps/usuarios/templates/listado.html
{% extends 'base.html' %}

{% load static %}
{% load  custom_tags %}
{% block title %} Publicaciones {% endblock %}
{% block secciontitle %} Listado de usuarios{% endblock %}

{% block css %}
<link href="{% static 'css/custom/usuarios.css' %} " rel="stylesheet">
{% endblock %}


{% block contentRow %}
{% include 'contentBody/contentRow.html' %}
{% endblock %}

{% block customSection %}
<div class="row  mb-3">
    <div class="  col-lg-12">
        <input type="text" class="form-control" id="btn_buscar_usuarios"
            placeholder="Buscar por usuario, nombre, correo, etc">
    </div>
    <!-- <input type="text" name="" id=""  > -->
</div>

<!-- {{query}} -->
<div class="table-responsive-md  table-responsive-sm">


    <table class="table table-sm mx-auto" id="tabla_usuarios">
        <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Usuario</th>
                <th scope="col">Nombre</th>
                <th scope="col">Correo</th>
                <th scope="col">Tipo usuario</th>
                <th scope="col">Estatus</th>
                {% if  request.session.is_administrador or request.session.is_gerente_ventas %}
                <th scope="col">Opciones</th>
                {% endif %}

            </tr>
        </thead>
        <tbody>
            {% for usu in usuarios %}

            <tr>
                <th scope="row">{{usu.id}}</th>
                <td>{{usu.username}}</td>
                <td>{{usu.first_name}} {{usu.lastname}}</td>
                <td>{{usu.email}}</td>
                <td>
                    {% if usu.is_administrador == 1 %}
                    Administrador
                    {% elif usu.is_supervisor == 1 %}
                    Supervisor
                    {% elif usu.is_gerente_ventas  == 1 %}
                    Gerente ventas
                    {% elif usu.is_vendedor == 1 %}
                    Vendedor
                    {% else %}
                    No asignado
                    {% endif %}

                </td>

                <td>
                    {% if usu.is_active == 1 %}
                    Activo
                    {% else %}
                    <span class="text-danger"> Desactivado</span>
                    {% endif %}
                </td>
                {% if  request.session.is_administrador or request.session.is_gerente_ventas %}
                <td>

                    <div class="btn-group">
                        <button style="color: #858796;" type="button" class="btn btn-link dropdown-toggle"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            opciones
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'actualizarUsuario' usu.id %}"
                                style="color: #858796;">Editar</a>
                            <!-- <a class="dropdown-item" href="#">Another action</a>
                          <a class="dropdown-item" href="#">Something else here</a> -->
                            <div class="dropdown-divider"></div>
                            {% if usu.is_active == 1 %}
                            <a class="dropdown-item" style="color: #858796;" href="#"
                                onclick="cambiar_estatus_usuario('{{usu.id}}','{{usu.username}}',0)">Desactivar</a>
                            {% else %}
                            <a class="dropdown-item" style="color: #858796;" href="#"
                                onclick="cambiar_estatus_usuario('{{usu.id}}','{{usu.username}}',1)">Activar</a>
                            {% endif %}

                        </div>
                    </div>
                </td>
                {% endif %}
            </tr>



            {% endfor %}
        </tbody>
    </table>
</div>







{% endblock %}


{% block javascript %}
<script src="{% static 'js/custom/usuarios/usuarios.js' %}"></script>
{% endblock %}

app/apps/usuarios/templates/login.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">




<style>
/* Change the white to any color ;) */
input:-webkit-autofill,
input:-webkit-autofill:hover, 
input:-webkit-autofill:focus, 
input:-webkit-autofill:active  {
    -webkit-box-shadow: 0 0 0 30px #55CEC2 inset !important;
}

input:-webkit-autofill {
    -webkit-text-fill-color: black !important;
}
</style>
<link href="{% static 'css/custom/usuarios.css' %} " rel="stylesheet">
<!-- <link href="{% static 'css/custom/clientes.css' %} " rel="stylesheet">
<link href="{% static 'css/custom/publicaciones.css' %} " rel="stylesheet"> -->


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body style="background-color: black;">
    <form action="{% url 'customLogin' %}"  method="post"
        class="border col-lg-5 col-md-10 col-sm-10 mx-auto centrar_login login"
        style="border: 1px black solid !important;">
        {% csrf_token %}

        <div class="centrar_login">
            <figure class=" mx-auto mt-3" style="width: 150px;">
                <img src="{% static 'img/custom/logo.png' %}" class='w-100' alt="">
            </figure>
            <p class="text-center text-danger" id="error">{{error}}</p>
            <div class="form-group centrar_horizontal">
                <input type="text" class=" login-input" id="id_username" name="username" required aria-describedby=""
                    placeholder="Usuario o correo">
            </div>


            <div class="form-group centrar_horizontal">

                <input type="password" class=" login-input" id="id_password" name="password" required
                    aria-describedby="" placeholder="Contraseña">
            </div>
            <div style="height: 20px;" ></div>
            <div class="d-flex justify-content-center align-items-center">
                <input type="submit" value="Ingresar" class="mb-5 btn btn-negro">
            </div>
            {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
        </div>
        <!-- </div> -->

    </form>
</body>

</html>




<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>


    <script>
        $(document).ready(function () {
        setTimeout(function(){ $("#error").hide('slow'); }, 3000);
        })
    </script>

app/apps/usuarios/templates/signup.html
{% extends 'base.html' %}

{% load static %}


{% load custom_tags %}

{% block title %} Registro usuarios {% endblock %}
{% block secciontitle %}Registro de usuarios{% endblock %}

{% block css %}
<link href="{% static 'css/custom/publicaciones.css' %} " rel="stylesheet">
<link href="{% static 'css/custom/clientes.css' %} " rel="stylesheet">
<link href="{% static 'css/custom/usuarios.css' %} " rel="stylesheet">
{% endblock %}




{% block customSection %}

<form action="/usuarios/registro-usuarios" class="border col-lg-7 mx-auto mb-5 form-sign" method="POST" id="signup_form">
    {% csrf_token %}

    <!-- {{form}} -->
    <figure class="   mx-auto mt-3" style="width: 120px;">
        <img src="{%static 'img/custom/account.png' %}" alt="" style="width: 100%;">
    </figure>
    <h3 class="text-center">{{mensaje}}</h3>
    
    <div class="col-lg-10 mx-auto">

        <div class="form-group">
            <label for="exampleInputEmail1">Usuario</label>
            <input type="text" class="form-control sin-bordes" name="username" maxlength="150" autofocus="" required=""
                id="id_username">

        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Nombre</label>
            <input type="text" class="form-control sin-bordes" name="first_name" maxlength="150" autofocus=""
                required="" id="id_first_name">

        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Apellidos</label>
            <input type="text" class="form-control sin-bordes" name="last_name" maxlength="150" autofocus="" required=""
                id="id_last_name">

        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Correo</label>
            <input type="email" class="form-control sin-bordes" name="email" maxlength="150" autofocus="" required=""
                id="id_email">
            <!-- <small id="" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Contraseña</label>
            <input type="password" class="form-control sin-bordes" name="password1" required="" id="id_password1">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Confirmar contraseña</label>
            <input type="password" class="form-control sin-bordes" name="password2" required="" id="id_password2">
        </div>
        <div class="form-group">
            <label for="exampleFormControlSelect1">Tipo de usuario</label>
            <select class="form-control sin-bordes" name="tipo_usuario" id="id_tipo_usuario" required="">
                <!-- {{tipos_usuarios.query}} -->
                {% for tipo in tipos_usuarios %}
                
                <option value="{{tipo.id}}">{{tipo.name}}</option>
                {% endfor %}

            </select>
        </div>
    </div>

    <div class="d-flex justify-content-center align-items-center">
        <input type="submit" class="btn btn-primary mt-3 mb-3 mx-auto"  id="btn_guardar_usuario" value="Guardar">
    </div>
    <!-- <div class="d-flex justify-content-center align-items-center">
        <input type="submit" class="btn btn-primary mt-3 mb-3 mx-auto" value="Guardar">
    </div> -->
</form>
{% endblock %}


{% block javascript %}
<script src="{% static 'js/custom/usuarios/usuarios.js' %}"></script>
{% endblock %}

app/apps/usuarios/templates/update.html
{% extends 'base.html' %}

{% load static %}


{% load custom_tags %}


{% block title %} Registro usuarios {% endblock %}
{% block secciontitle %}Modificación de usuario{% endblock %}

{% block css %}
<link href="{% static 'css/custom/publicaciones.css' %} " rel="stylesheet">
<link href="{% static 'css/custom/clientes.css' %} " rel="stylesheet">
<link href="{% static 'css/custom/usuarios.css' %} " rel="stylesheet">
{% endblock %}




{% block customSection %}
{% if existe %}

<form action="/usuarios/metodoActualizar" class="border col-lg-12 col-md-12 col-sm-12 mx-auto mb-5 form-sign"
    method="POST" id="update_form_user">
    {% csrf_token %}

    <div class="d-flex justify-content-between align-items-center mt-3">
        <div class="row col-lg-12">
            <div class="form-group col-lg-6 ">
                <label for="exampleInputEmail1">Usuario</label>
                <input type="text" name="usuario" value="{{usuario.username}}" class="form-control sin-bordes" id="id_usuario"
                    readonly aria-describedby=""  readonly>
                

            </div>
            <div class="form-group col-lg-6">
                <label for="exampleFormControlSelect1">Tipo de usuario</label>
                <select class="form-control sin-bordes" name="tipo_usuario" id="id_tipo_usuario" required=""  onchange="grupos_usuarios()">
                    <!-- {{tipos_usuarios.query}} -->
                    {% for tipo in tipos_usuarios %}
                    {% if tipo.id  ==  grupo %}
                    <option selected value="{{tipo.id}}">{{tipo.name}}</option>
                    {% else %}
                    <option value="{{tipo.id}}">{{tipo.name}}</option>

                    {% endif %}
                    {% endfor %}

                </select>
            </div>

        </div>
    </div>

    <div class="d-flex justify-content-between align-items-center mt-3">
        <div class="row col-lg-12">
            <div class="form-group col-lg-6 ">
                <label for="exampleInputEmail1">Nombre</label>
                <input type="text" name="first_name" value="{{usuario.first_name}}" class="form-control sin-bordes"  
                    aria-describedby="emailHelp" placeholder="Nombre" id="id_first_name">

            </div>
            <div class="form-group col-lg-6 ">
                <label for="exampleInputEmail1">Apellidos</label>
                <input type="text" value="{{usuario.last_name}}" class="form-control sin-bordes" id="id_last_name" 
                    aria-describedby="emailHelp" placeholder="Apellidos" name="last_name">

            </div>



        </div>
    </div>

    <div class="d-flex justify-content-between align-items-center mt-3">
        <div class="row col-lg-12">
            <div class="form-group col-lg-6 ">
                <label for="exampleInputEmail1">Correo</label>
                <input type="text" value="{{usuario.email}}" class="form-control sin-bordes" id="id_email" 
                    aria-describedby="emailHelp" placeholder="Correo" name="email">

            </div>
            <div class="form-group col-lg-6">
                <label for="exampleFormControlSelect1">Estatus</label>
                <select class="form-control sin-bordes" name="estatus" id="id_estatus" required="">
                    <!-- {{tipos_usuarios.query}} -->
        

                    {% for k, v in estatus.items %}
                    {% if  v == usuario.is_active %}
                    <option selected value="{{v}}">{{k}}</option>
                    {% else %}
                    <option  value="{{v}}">{{k}}</option>
                    {% endif %}
                    {% endfor %}


                </select>
            </div>



        </div>
    </div>

    <div class="d-flex justify-content-between align-items-center mt-3">
        <div class="row col-lg-12">
            <!-- <div class="form-group col-lg-6 ">
                <label for="exampleInputEmail1">Correo</label>
                <input type="text" value="{{usuario.email}}" class="form-control sin-bordes" id="id_email" 
                    aria-describedby="emailHelp" placeholder="Correo" name="email">

            </div> -->
            <div class="form-group col-lg-6 d-none">
                <label for="exampleFormControlSelect1">Tipo vendedor</label>
                <select class="form-control sin-bordes" name="vendedor" id="id_estatus" required="">

                    {% if vendedor %}
                        {%if tipo_vendedor  ==  1 %}
                        <option selected value="1">Gerente</option>
                        <option  value="0">Vendedor </option>
                        <option  value="2">No es vendedor </option>

                        {% else %}
                        <option selected value="0">Vendedor</option>
                        <option  value="2">No es vendedor </option>
                        <option  value="1">Gerente </option>

                        {% endif %}
                    {% else %}
                    <option selected value="2">No es vendedor </option>
                    <option  value="0">Vendedor </option>
                    <option  value="1">Gerente </option>

                    {% endif %}


                </select>
            </div>



        </div>
    </div>
    <input type="hidden" name="id_identificador" value="{{usuario.id}}">
    
    <div class="d-flex justify-content-center align-items-center mb-3 mt-3">
        {% if  request.session.is_administrador or request.session.is_supervisor %}
        <button type="submit" class="btn btn-primary" id="btn-modificar-usuario">Modificar</button>
        {% else %}
        <p class="text-center text-danger">No tienes permisos para modificar usuarios</p>
    {% endif %}

    </div>




</form>



{% else %}
<div class=" " style="position: relative;">
    <div id="not_found" class="content-not-found centrado">

    </div>

</div>

{% endif %}
{% endblock %}


{% block javascript %}
<script src="{% static 'js/custom/usuarios/usuarios.js' %}"></script>
{% endblock %}